### ISSUE TITLE
yoskoslowich

### ISSUE THREAD

**Issue by yoskoslowich** [lucianaa/topicosIC#14]

**Comment by yoskoslowich** [comment]
Caminho do Python no windows
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64

**Comment by yoskoslowich** [comment]
Para abrir o Python no Windows abra o CMD e digite:
C:\"Program Files (x86)"\"Microsoft Visual Studio"\Shared\Python36_64\python

**Comment by lucianaa** [comment]
Qual o repositório?

**Comment by yoskoslowich** [comment]
https://github.com/yoskoslowich/topicosIC
