### ISSUE TITLE
BrenoPeixoto

### ISSUE THREAD

**Issue by BrenoPeixotobr** [lucianaa/topicosIC#22]

**Comment by lucianaa** [comment]
Qual o repositório?

**Comment by BrenoPeixotobr** [comment]
https://github.com/BrenoPeixotobr/topicosic.git




Breno Peixoto dos Santos
Técnico em Redes de Computadores
Graduando de Ciência da Computação - Instituto Federal  do Norte de Minas
Gerais


Em sáb, 15 de set de 2018 às 09:45, Luciana Balieiro <
notifications@github.com> escreveu:
